name: Healthcheck
on:
  schedule:
    - cron: '0 */8 * * *'
jobs:
  simple-health-check:
    runs-on: ubuntu-latest
    steps:
      - name: Ping the server
      run: |
       curl -I ${{ vars.SERVER_ENDPOINT }} | grep 'HTTP/2 200'
