name: Run E2E
on:
  workflow_dispatch:
jobs:
  run-e2e-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    step:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-verstion: lts/*
      - name: Install dependecies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright Tests
        run: npx playwright test
      - use: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
